version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install for a static website"
  build:
    commands:
      - echo "No build required for static website"
  post_build:
    commands:
      - echo "Syncing files to S3"
      - ls src/mystatic  # List contents to verify directory presence
      - aws s3 sync src/mystatic s3://my-first-static-website123 --delete
